language: python
python:
  - 2.7
before_install:
  # Print NumPy version that is already installed by Travis CI:
  - python -c "import numpy; print numpy.__version__"
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran liblapack-pic
  - pip install --use-mirrors matplotlib
  
install:
  - python setup.py install
  
before_script:
  - cat /proc/cpuinfo
  - gfortran -v
  
script:
  - export CLAW=${pwd}
  - cd $CLAW/pyclaw
  - nosetests
  - export FC=gfortran
  - cd $CLAW/classic
  - nosetests
  - cd $CLAW/amrclaw
  - nosetests
  - cd $CLAW/geoclaw
  - nosetests
  
notifications:
  email: false
