package:
  name: clawpack
  version: 5.4.1

source:
  path: ..


requirements:
  build:
    - python
    - numpy

  run:
    - python
    - six
    - numpy
    - scipy
    - matplotlib
    - mpi4py
    - petsc4py
    - h5py-parallel

build:
  number: 0

test:
    imports:
        - clawpack.pyclaw
        - clawpack.petclaw
        - clawpack.pyclaw.fileio.hdf5
        - clawpack.riemann.euler_4wave_2D
