package:
  name: clawpack
  version: 5.4.0

source:
  path: ..


requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy
    - matplotlib
    - hdf5-parallel
    - petsc4py
    - scipy
    - six
    - mpi4py

build:
  number: 0

test:
    imports:
        - clawpack.pyclaw
        - clawpack.petclaw
